definitions:
  domain.Apotek:
    properties:
      admin_id:
        type: string
      alamat:
        type: string
      created_at:
        type: string
      deskripsi:
        description: Field Baru
        type: string
      id:
        type: string
      jam_buka:
        type: string
      jam_tutup:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      nama:
        type: string
      phone_number:
        description: Field Baru
        type: string
      rejection_reason:
        type: string
      verification_status:
        description: APPROVED / REJECTED
        type: string
    type: object
  dto.APIResponse:
    properties:
      data: {}
      message:
        example: success
        type: string
      success:
        example: true
        type: boolean
    type: object
  dto.AdminRequest:
    properties:
      email:
        example: admin@apotek.com
        type: string
      nama:
        example: Admin Apotek
        type: string
      password:
        example: password123
        type: string
    type: object
  dto.AuthResponse:
    properties:
      email:
        type: string
      name:
        example: Budi
        type: string
      role:
        example: user
        type: string
      token:
        example: jwt_token_here
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      message:
        example: error message
        type: string
      success:
        example: false
        type: boolean
    type: object
  dto.GoogleLoginRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  dto.LoginRequest:
    properties:
      email:
        example: budi@email.com
        type: string
      password:
        example: password123
        type: string
    type: object
  dto.MetaPagination:
    properties:
      limit:
        example: 10
        type: integer
      page:
        example: 1
        type: integer
      total:
        example: 100
        type: integer
      total_page:
        example: 10
        type: integer
    type: object
  dto.ObatRequest:
    properties:
      harga:
        example: 5000
        type: number
      nama:
        example: Paracetamol
        type: string
      stok:
        example: 50
        type: integer
    type: object
  dto.PaginatedResepResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.ResepResponse'
        type: array
      meta:
        $ref: '#/definitions/dto.MetaPagination'
    type: object
  dto.PaymentNotification:
    properties:
      order_id:
        type: string
      payment_type:
        type: string
      signature_key:
        type: string
      transaction_status:
        type: string
    type: object
  dto.RegisterAdminRequest:
    properties:
      alamat:
        type: string
      deskripsi:
        type: string
      email:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      nama_apotek:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        type: string
    required:
    - alamat
    - email
    - latitude
    - longitude
    - nama_apotek
    - name
    - password
    - phone_number
    type: object
  dto.RegisterRequest:
    properties:
      email:
        example: budi@email.com
        type: string
      name:
        example: Budi
        type: string
      password:
        example: password123
        type: string
    type: object
  dto.ResepResponse:
    properties:
      file_url:
        type: string
      id:
        type: integer
      status:
        type: string
      transaksi_id:
        type: integer
    type: object
  dto.UpdateResepStatusRequest:
    properties:
      status:
        example: approved
        type: string
    required:
    - status
    type: object
  dto.VerifyAdminRequest:
    properties:
      action:
        description: approved atau rejected
        example: approved
        type: string
      admin_id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      notes:
        example: Dokumen apotek valid dan lengkap
        type: string
    required:
    - action
    - admin_id
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Medifinder Application
  title: Medifinder API
  version: "1.0"
paths:
  /admin/apotek:
    get:
      description: Mengambil data lengkap apotek yang dikelola oleh admin yang sedang
        login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Apotek'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Melihat Profil Apotek Saya (Admin Only)
      tags:
      - Admin Apotek
    post:
      produces:
      - application/json
      responses: {}
      summary: Buat Apotek Baru
      tags:
      - Apotek
    put:
      produces:
      - application/json
      responses: {}
      summary: Update Profil Apotek Sendiri
      tags:
      - Apotek
  /admin/obat:
    get:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Lihat stok obat saya (Admin Only)
      tags:
      - Admin Obat
    post:
      consumes:
      - application/json
      description: Admin apotek menambahkan obat ke apotek miliknya
      parameters:
      - description: Data obat
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ObatRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Tambahkan obat baru
      tags:
      - Admin Obat
  /admin/obat/:id:
    delete:
      responses: {}
      summary: Hapus obat
      tags:
      - Admin Obat
    put:
      responses: {}
      summary: Update data obat
      tags:
      - Admin Obat
  /admin/resep:
    get:
      description: Admin apotek melihat daftar resep yang diunggah user
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Limit data (max 50)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.PaginatedResepResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Daftar resep
      tags:
      - Admin Resep
  /admin/resep/{id}:
    put:
      consumes:
      - application/json
      description: Admin apotek memverifikasi atau menolak resep
      parameters:
      - description: ID Resep
        in: path
        name: id
        required: true
        type: integer
      - description: Status resep
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateResepStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update status resep
      tags:
      - Admin Resep
  /admin/transaksi:
    get:
      responses: {}
      security:
      - BearerAuth: []
      summary: Riwayat transaksi masuk (Admin Apotek)
      tags:
      - Admin Transaksi
  /apotek/{id}/obat:
    get:
      parameters:
      - description: Apotek ID
        in: path
        name: id
        required: true
        type: string
      - description: Search by Name
        in: query
        name: name
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Lihat daftar obat di apotek tertentu (Public)
      tags:
      - Obat
  /apotek/nearby:
    get:
      produces:
      - application/json
      responses: {}
      summary: Mencari Apotek Terdekat & Buka
      tags:
      - Apotek
  /google-login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Google token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GoogleLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login via Google
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login user
      tags:
      - Auth
  /me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Ambil profil user yang sedang login
      tags:
      - Auth
  /payment/notify:
    post:
      consumes:
      - application/json
      description: Endpoint untuk menerima notifikasi pembayaran dari Midtrans
      parameters:
      - description: Midtrans notification payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/dto.PaymentNotification'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.APIResponse'
      summary: Callback notifikasi pembayaran
      tags:
      - Payment
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Register data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Registrasi user
      tags:
      - Auth
  /register-admin:
    post:
      consumes:
      - application/json
      description: Pendaftaran mandiri untuk Admin Apotek beserta data apoteknya
      parameters:
      - description: Data Registrasi Admin Apotek
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterAdminRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Registrasi Mandiri Admin Apotek
      tags:
      - Auth
  /resep:
    post:
      consumes:
      - multipart/form-data
      description: User mengunggah resep sebagai dokumen pendukung transaksi
      parameters:
      - description: File resep (max 5MB)
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Upload resep dokter
      tags:
      - Resep
  /superadmin/admin:
    get:
      responses: {}
      security:
      - BearerAuth: []
      summary: Daftar semua admin apotek
      tags:
      - SuperAdmin
    post:
      parameters:
      - description: Data admin
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AdminRequest'
      responses: {}
      security:
      - BearerAuth: []
      summary: Buat akun admin apotek baru
      tags:
      - SuperAdmin
  /superadmin/admin/{id}/status:
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID Admin Apotek
        in: path
        name: id
        required: true
        type: string
      - description: 'Status baru: ''approved'' atau ''suspended'''
        in: body
        name: request
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Ubah status admin apotek (Suspend / Activate)
      tags:
      - Super Admin
  /superadmin/pengajuan:
    get:
      parameters:
      - default: 1
        description: Halaman (default 1)
        in: query
        name: page
        type: integer
      - default: 10
        description: Jumlah data per halaman (default 10)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Ambil daftar admin apotek yang masih pending (butuh verifikasi)
      tags:
      - SuperAdmin
  /superadmin/verifikasi:
    post:
      consumes:
      - application/json
      parameters:
      - description: 'Data Verifikasi (Action: approved/rejected)'
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.VerifyAdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Verifikasi pendaftaran admin apotek (Approve / Reject)
      tags:
      - SuperAdmin
  /transaksi:
    get:
      parameters:
      - description: Filter Status
        in: query
        name: status
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Riwayat transaksi user
      tags:
      - Transaksi
  /transaksi/{id}:
    get:
      parameters:
      - description: Transaksi ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Detail transaksi
      tags:
      - Transaksi
swagger: "2.0"
